require("dotenv").config();
const fs=require("fs"),path=require("path"),https=require("https"),express=require("express"),cors=require("cors"),helmet=require("helmet"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),mongoose=require("mongoose"),multer=require("multer"),rateLimit=require("express-rate-limit"),nodemailer=require("nodemailer"),sharp=require("sharp");
const app=express(); app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}})); app.use(cors()); app.use(express.json({limit:"2mb"})); app.use("/api/auth",rateLimit({windowMs:900000,limit:50})); app.get("/health",(_,r)=>r.json({status:"ok",service:"pothole-guard-api"}));
const User=mongoose.model("User",new mongoose.Schema({name:String,email:{type:String,unique:true,lowercase:true},password:String,role:{type:String,enum:["user","admin"],default:"user"}},{timestamps:true}));
const Pothole=mongoose.model("Pothole",new mongoose.Schema({latitude:Number,longitude:Number,location:{type:{type:String,enum:["Point"],default:"Point"},coordinates:{type:[Number],index:"2dsphere"}},confidence:Number,imageUrl:String,boundingBox:Object,detectedBy:{type:mongoose.Schema.Types.ObjectId,ref:"User"},timestamp:{type:Date,default:Date.now},status:{type:String,enum:["DETECTED","VERIFIED","REPORTED_TO_RTO","IN_PROGRESS","RESOLVED"],default:"DETECTED"},detectionCount:{type:Number,default:1},adminNotes:String},{timestamps:true}));
const auth=(req,res,next)=>{try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({message:"Authentication required"});req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET);next()}catch(e){res.status(401).json({message:"Invalid or expired token"})}}, admin=(req,res,next)=>req.user.role==="admin"?next():res.status(403).json({message:"Admin access required"}), sign=u=>jwt.sign({id:u._id.toString(),role:u.role,email:u.email},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||"7d"});
app.post("/api/auth/register",async(req,res,next)=>{try{const {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:"name,email,password(6+) required"});if(await User.findOne({email}))return res.status(409).json({message:"Email already registered"});const u=await User.create({name,email,password:await bcrypt.hash(password,12)});res.status(201).json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){next(e)}});
app.post("/api/auth/login",async(req,res,next)=>{try{const u=await User.findOne({email:req.body.email});if(!u||!(await bcrypt.compare(req.body.password||"",u.password)))return res.status(401).json({message:"Invalid credentials"});res.json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){next(e)}});
app.get("/api/auth/me",auth,async(req,res,next)=>{try{res.json({user:await User.findById(req.user.id).select("-password")})}catch(e){next(e)}});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(_,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});
let ort,session;const modelPath="/tmp/best.onnx";
function downloadModel(){return new Promise((resolve,reject)=>{const get=u=>https.get(u,r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location)return get(r.headers.location);if(r.statusCode!==200)return reject(new Error("Model download failed: "+r.statusCode));const f=fs.createWriteStream(modelPath);r.pipe(f);f.on("finish",()=>f.close(resolve))}).on("error",reject);get(process.env.MODEL_URL)})}
async function detect(buf){if(!ort)ort=require("onnxruntime-node");if(!fs.existsSync(modelPath))await downloadModel();session ||= await ort.InferenceSession.create(modelPath);const x=await sharp(buf).removeAlpha().resize(640,640,{fit:"contain",background:{r:114,g:114,b:114}}).raw().toBuffer();const a=new Float32Array(3*640*640),n=640*640;for(let i=0;i<n;i++){a[i]=x[3*i]/255;a[n+i]=x[3*i+1]/255;a[2*n+i]=x[3*i+2]/255}const o=await session.run({[session.inputNames[0]]:new ort.Tensor("float32",a,[1,3,640,640])}),t=o[session.outputNames[0]],d=t.data,N=t.dims.at(-1),R=t.dims.at(-2),c=Number(process.env.DETECTION_CONFIDENCE||.25),out=[];for(let i=0;i<N;i++){let s=0,k=0;for(let j=0;j<R-4;j++){const v=d[(4+j)*N+i];if(v>s){s=v;k=j}}if(s<c)continue;const cx=d[i],cy=d[N+i],w=d[2*N+i],h=d[3*N+i];out.push({class:"pothole",classId:k,confidence:s,box:{x1:Math.max(0,cx-w/2),y1:Math.max(0,cy-h/2),x2:Math.min(640,cx+w/2),y2:Math.min(640,cy+h/2)}})}return out}
app.post("/api/detect",auth,upload.single("image"),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({message:"image is required"});const detections=await detect(req.file.buffer);res.json({count:detections.length,detections})}catch(e){next(e)}});
const hav=(a,b,c,d)=>{const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,z=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))};
app.post("/api/potholes",auth,async(req,res,next)=>{try{const {latitude,longitude,confidence,imageUrl,boundingBox,timestamp,gpsAccuracy}=req.body;if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||!Number.isFinite(confidence))return res.status(400).json({message:"latitude, longitude and confidence are required"});if(gpsAccuracy&&gpsAccuracy>Number(process.env.MAX_GPS_ACCURACY_METERS||50))return res.status(422).json({message:"GPS accuracy is too low"});const near=await Pothole.find({latitude:{$gte:latitude-.001,$lte:latitude+.001},longitude:{$gte:longitude-.001,$lte:longitude+.001}}).limit(200);const d=near.find(p=>hav(latitude,longitude,p.latitude,p.longitude)<=Number(process.env.DUPLICATE_RADIUS_METERS||15));if(d){d.detectionCount++;d.confidence=Math.max(d.confidence,confidence);await d.save();return res.json({duplicate:true,pothole:d})}const p=await Pothole.create({latitude,longitude,location:{type:"Point",coordinates:[longitude,latitude]},confidence,imageUrl,boundingBox,timestamp:timestamp||new Date(),detectedBy:req.user.id});res.status(201).json({duplicate:false,pothole:p})}catch(e){next(e)}});
app.get("/api/potholes",auth,async(req,res,next)=>{try{const q=req.user.role==="admin"?{}:{detectedBy:req.user.id};if(req.query.status)q.status=req.query.status;const items=await Pothole.find(q).sort({timestamp:-1}).limit(1000);res.json({items,total:items.length})}catch(e){next(e)}});
app.get("/api/potholes/nearby",auth,async(req,res,next)=>{try{const lat=Number(req.query.lat),lng=Number(req.query.lng),radius=Number(req.query.radius||1000);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({message:"lat,lng required"});res.json({items:await Pothole.find({location:{$near:{$geometry:{type:"Point",coordinates:[lng,lat]},$maxDistance:radius}}}).limit(500)})}catch(e){next(e)}});
app.patch("/api/potholes/:id",auth,admin,async(req,res,next)=>{try{const p=await Pothole.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!p)return res.status(404).json({message:"Pothole not found"});res.json({pothole:p})}catch(e){next(e)}});
app.delete("/api/potholes/:id",auth,admin,async(req,res,next)=>{try{if(!await Pothole.findByIdAndDelete(req.params.id))return res.status(404).json({message:"Pothole not found"});res.status(204).end()}catch(e){next(e)}});
app.post("/api/reports/email",auth,admin,async(req,res,next)=>{try{const items=await Pothole.find({status:{$ne:"RESOLVED"}}).sort({timestamp:-1}).limit(10000);const rows=items.map(p=>'<tr><td>'+p._id+'</td><td>'+p.latitude+'</td><td>'+p.longitude+'</td><td>'+Number(p.confidence).toFixed(3)+'</td><td>'+p.status+'</td></tr>').join("");const html='<h2>Pothole Detection Report</h2><p>'+new Date().toISOString()+'</p><table border="1" cellpadding="6"><tr><th>ID</th><th>Latitude</th><th>Longitude</th><th>Confidence</th><th>Status</th></tr>'+rows+'</table>';const tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE)!=="false",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await tr.sendMail({from:process.env.SMTP_USER,to:process.env.RTO_EMAIL,subject:"Pothole Detection Report",html});res.json({sent:true,to:process.env.RTO_EMAIL,count:items.length})}catch(e){next(e)}});
app.use((e,_,res,__)=>(console.error(e),res.status(500).json({message:e.message||"Internal server error"})));
mongoose.connect(process.env.MONGODB_URI).then(()=>app.listen(Number(process.env.PORT||10000),()=>console.log("API started"))).catch(e=>{console.error(e);process.exit(1)});
